<?php



$codeDay = date('w'); //Obtenemos la clave del día (0-6)

$getDate = date('Y-m-d');

//$getDate = '2024-07-19';

//$codeDay = '4';



/** Historial de Asistencias */



$sqlBiometricTimeClock = "SELECT DISTINCT ATT.NOM_ID, ATT.CODE_DAY, ATT.ATTENDANCE_DATE RECORD_DATE, CDY.NAME_DAY, ASH.BREAK_TIME
, IFNULL( (SELECT ATE.JUSTIFY FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 1 ORDER BY ATE.JUSTIFY DESC LIMIT 1), '') JUSTIFY
, IFNULL( (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 1 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), '') CHECK_IN
, IFNULL( (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 2 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), '') CHECK_OUT
, IFNULL( (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 3 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), '') BREAK_START
, IFNULL( (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 4 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), '') BREAK_END
, IFNULL( (SELECT CIN.DESCRIP_TINC FROM admin_attendance ATE INNER JOIN code_incidence CIN ON CIN.CODE_TINC = ATE.TINC WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 1 ORDER BY ATE.ATTENDANCE_TIME DESC LIMIT 1), '') STATUS
, IFNULL( TIMEDIFF(
    IFNULL( (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 4 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), ''),
    IFNULL( (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 3 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), '')), '') BREAK_TIME_TAKEN
FROM admin_attendance ATT
INNER JOIN employed EMP ON EMP.ID_NOM = ATT.NOM_ID
INNER JOIN code_days CDY ON CDY.CODE_DAY = (DAYOFWEEK(ATT.ATTENDANCE_DATE) - 1)
LEFT OUTER JOIN admin_schedules ASH ON ASH.CODE_SCHEDULE = EMP.SCHEDULE_GROUP AND ASH.CODE_DAY = CDY.CODE_DAY
WHERE ATT.NOM_ID = '$user_active' AND ATT.ATTENDANCE_DATE BETWEEN 
        (SELECT PRP.START_DATE FROM payroll_period PRP WHERE PRP.ID = '$payrollPeriodID')  AND (SELECT PRP.END_DATE FROM payroll_period PRP WHERE PRP.ID = '$payrollPeriodID') ORDER BY ATT.ATTENDANCE_DATE ASC";





/** Validar qué estatus tendrá la asistencia del colaborador */

$sql_get_incidence = "SELECT 
        EMP.ID_NOM, ASH.*
    FROM employed EMP 
    INNER JOIN admin_schedules ASH ON ASH.CODE_SCHEDULE = EMP.SCHEDULE_GROUP
    WHERE EMP.ID_NOM = '$user_active' AND ASH.CODE_DAY = '$codeDay'";



/** Validar Retardos para Falta por Retardos */



$sql_countDelays = "SELECT
        AAT.ATTENDANCE_DATE, AAT.TINC
    FROM admin_attendance AAT
    INNER JOIN payroll_period PRP ON AAT.ATTENDANCE_DATE BETWEEN PRP.START_DATE AND PRP.END_DATE
    WHERE '$getDate' BETWEEN PRP.START_DATE AND PRP.END_DATE AND AAT.TINC IN (2,8) AND AAT.IN_OUT = 1 AND NOM_ID = '$user_active'
    ORDER BY AAT.ATTENDANCE_DATE";


/** Validar registros de Asistencia del día de ayer */

$sql_attendance_today =
    "SELECT DISTINCT ATT.NOM_ID, ATT.CODE_DAY, ATT.ATTENDANCE_DATE, CDY.NAME_DAY, ASH.BREAK_TIME
, IFNULL( (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 1 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), '') CHECK_IN
, IFNULL( (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 2 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), '') CHECK_OUT
, IFNULL( (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 3 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), '') BREAK_START
, IFNULL( (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 4 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), '') BREAK_END
, IFNULL( TIMEDIFF(
    IFNULL( (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 4 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), ''),
    IFNULL( (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 3 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), '')), '') BREAK_TIME_TAKEN
FROM admin_attendance ATT
INNER JOIN employed EMP ON EMP.ID_NOM = ATT.NOM_ID
INNER JOIN code_days CDY ON CDY.CODE_DAY = (DAYOFWEEK(ATT.ATTENDANCE_DATE) - 1)
LEFT OUTER JOIN admin_schedules ASH ON ASH.CODE_SCHEDULE = EMP.SCHEDULE_GROUP AND ASH.CODE_DAY = CDY.CODE_DAY
WHERE ATT.NOM_ID = '$user_active' and ATT.ATTENDANCE_DATE = '$getDate'";



/** Validar registros de Asistencia del día de ayer */

$sql_attendance_yesterday =
    "SELECT DISTINCT ATT.NOM_ID, ATT.CODE_DAY, ATT.ATTENDANCE_DATE RECORD_DATE, CDY.NAME_DAY, ASH.BREAK_TIME
, IFNULL( (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 1 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), '') CHECK_IN
, IFNULL( (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 2 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), '') CHECK_OUT
, IFNULL( (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 3 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), '') BREAK_START
, IFNULL( (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 4 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), '') BREAK_END
, IFNULL( TIMEDIFF(
    IFNULL( (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 4 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), ''),
    IFNULL( (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 3 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), '')), '') BREAK_TIME_TAKEN
FROM admin_attendance ATT
INNER JOIN employed EMP ON EMP.ID_NOM = ATT.NOM_ID
INNER JOIN code_days CDY ON CDY.CODE_DAY = (DAYOFWEEK(ATT.ATTENDANCE_DATE) - 1)
LEFT OUTER JOIN admin_schedules ASH ON ASH.CODE_SCHEDULE = EMP.SCHEDULE_GROUP AND ASH.CODE_DAY = CDY.CODE_DAY
WHERE ATT.NOM_ID = '$user_active' and ATT.ATTENDANCE_DATE = DATE_ADD('$getDate', INTERVAL -1 DAY);";
