<?php

$sql_get_teachers = "SELECT 
    DISTINCT
        ACS.PK, ACS.PERSON_CODE_ID, ASE.LONG_DESC ACADEMIC_SESSION, ASE.CODE_VALUE_KEY CODE_SESSION,
        CONCAT(ACS.NAME,' ',ACS.LAST_NAME,' ',ACS.Last_Name_Prefix) DOC_NAME,
        ACS.DEGREE, ACS.SECTION, ACS.PROGRAM, ACS.PROGRAM, ACS.CURRICULUM,
        ACS.CURRICULUM, ACS.BUILDING, ACS.ROOM, ACS.CODE_DAY,
        ACS.GENERAL_ED, ACS.EVENT, ACS.START_CLASS, ACS.DELAY_CLASS, ACS.MAX_DELAY_CLASS, ACS.END_CLASS,
        (SELECT ACT.TINC FROM academic_attendance ACT WHERE ACT.ATTENDANCE_DATE = '$today' AND ACT.SCHEDULE_ID = ACS.PK AND ACT.IN_OUT = 1 LIMIT 1) ATTENDANCE_TINC,
        (SELECT CIN.DESCRIP_TINC FROM academic_attendance ACT INNER JOIN code_incidence CIN ON CIN.CODE_TINC = ACT.TINC WHERE ACT.ATTENDANCE_DATE = '$today' AND ACT.SCHEDULE_ID = ACS.PK AND ACT.IN_OUT = 1 LIMIT 1) ATTENDANCE_STATUS, 
        (SELECT SUBSTRING( ACT.ATTENDANCE_TIME, 1, 8) FROM academic_attendance ACT WHERE ACT.ATTENDANCE_DATE = '$today' AND ACT.SCHEDULE_ID = ACS.PK AND ACT.IN_OUT = 1 LIMIT 1) ATTENDANCE_START_CLASS,
        (SELECT SUBSTRING( ACT.ATTENDANCE_TIME, 1, 8) FROM academic_attendance ACT WHERE ACT.ATTENDANCE_DATE = '$today' AND ACT.SCHEDULE_ID = ACS.PK AND ACT.IN_OUT = 2 LIMIT 1) ATTENDANCE_END_CLASS,
        (SELECT IF(ACT.TINC = '11', ACT.ACADEMIC_ID, '') FROM academic_attendance ACT WHERE ACT.ATTENDANCE_DATE = '$today' AND ACT.SCHEDULE_ID = ACS.PK AND ACT.IN_OUT = 1 LIMIT 1) TEACHER_CLASS
    FROM academic_schedules ACS
    INNER JOIN code_sesion_academic ASE ON ASE.CODE_VALUE_KEY = ACS.ACADEMIC_SESSION
    INNER JOIN academic_calendar ACL ON ACL.SessionPeriodId = ACS.SessionPeriodId
    WHERE '$today' BETWEEN ACL.START_DATE AND ACL.END_DATE AND ACS.CODE_DAY = '$codeDay' AND ACS.PROGRAM = '$program'
        AND ASE.CODE_NOM = '$user_sesion'
    ORDER BY ATTENDANCE_STATUS ASC, ACS.START_CLASS ASC";

$sql_teacher_attendance = "SELECT 
	DISTINCT
	CDY.NAME_DAY,
    AAT.AttendanceId,
    CONCAT(DOC.NAME,' ',DOC.LAST_NAME,' ',DOC.Last_Name_Prefix) NAME,
    CSA.LONG_DESC,
    AAT.ACADEMIC_ID,
    AAT.CURRICULUM,
    AAT.ROOM_ID,
    AAT.EVENT_ID,
    (SELECT ATE.CLASS_SUMMARY FROM academic_attendance ATE INNER JOIN code_incidence CIN ON CIN.CODE_TINC = ATE.TINC WHERE ATE.AttendanceId = AAT.AttendanceId AND ATE.IN_OUT = 1) CLASS_SUMMARY,
    (SELECT CIN.DESCRIP_TINC FROM academic_attendance ATE INNER JOIN code_incidence CIN ON CIN.CODE_TINC = ATE.TINC WHERE ATE.AttendanceId = AAT.AttendanceId AND ATE.IN_OUT = 1) INCIDENCE,
    (SELECT SUBSTRING( ATE.ATTENDANCE_TIME, 1, 8) FROM academic_attendance ATE WHERE ATE.AttendanceId = AAT.AttendanceId AND ATE.IN_OUT = 1) IN_TIME,
    (SELECT SUBSTRING( ATE.ATTENDANCE_TIME, 1, 8) FROM academic_attendance ATE WHERE ATE.AttendanceId = AAT.AttendanceId AND ATE.IN_OUT = 2) OUT_TIME,
    (SELECT ATE.JUSTIFY FROM academic_attendance ATE WHERE ATE.AttendanceId = AAT.AttendanceId AND ATE.IN_OUT = 1) JUSTIFY,
    (SELECT ATE.COMMENT FROM academic_attendance ATE WHERE ATE.AttendanceId = AAT.AttendanceId AND ATE.IN_OUT = 1) COMMENT
    FROM academic_attendance AAT
    INNER JOIN code_days CDY ON CDY.CODE_DAY = AAT.CODE_DAY
    INNER JOIN code_sesion_academic CSA ON CSA.CODE_VALUE_KEY = AAT.SESSION
    INNER JOIN academic_schedules DOC ON DOC.PERSON_CODE_ID = AAT.ACADEMIC_ID
    WHERE ATTENDANCE_DATE = '$selectedDay' AND AAT.PROGRAM = '$program' AND AAT.IN_OUT = '1'
    AND CSA.CODE_NOM = '$user_sesion'";

$sqlTeachersReport = "SELECT 
    DISTINCT
    CLD.CALENDAR_DATE
    , DYS.NAME_DAY
    , ACL.ACADEMIC_TERM
    , ACL.ACADEMIC_SESSION
    , ASH.PERSON_CODE_ID
    , CONCAT(ASH.NAME,' ',ASH.LAST_NAME,' ',ASH.Last_Name_Prefix) ACA_NAME
    , ASH.DEGREE
    , ASH.PROGRAM
    , ASH.CURRICULUM
    , ASH.GENERAL_ED
    , ASH.SERIAL_ID
    , ASH.ROOM
    , ASH.EVENT
    , ASH.START_CLASS
    , ASH.END_CLASS
    , (SELECT SUBSTRING( AAT.ATTENDANCE_TIME,1,8) FROM academic_attendance AAT WHERE ASH.PK = AAT.SCHEDULE_ID AND AAT.ATTENDANCE_DATE = CLD.CALENDAR_DATE AND AAT.IN_OUT = '1' LIMIT 1) CLASS_IN
    , (SELECT SUBSTRING( AAT.ATTENDANCE_TIME,1,8) FROM academic_attendance AAT WHERE ASH.PK = AAT.SCHEDULE_ID AND AAT.ATTENDANCE_DATE = CLD.CALENDAR_DATE AND AAT.IN_OUT = '2' LIMIT 1) CLASS_OUT
    , (SELECT CIN.DESCRIP_TINC FROM academic_attendance AAT INNER JOIN code_incidence CIN ON CIN.CODE_TINC = AAT.TINC WHERE ASH.PK = AAT.SCHEDULE_ID AND AAT.ATTENDANCE_DATE = CLD.CALENDAR_DATE AND AAT.IN_OUT = '1' LIMIT 1) CLASS_INCIDENCE
    FROM calendar CLD 
    INNER JOIN code_days DYS ON DYS.CODE_DAY = CLD.CODE_DAY
    INNER JOIN academic_schedules ASH ON ASH.CODE_DAY = CLD.CODE_DAY
    INNER JOIN code_sesion_academic SES ON SES.CODE_VALUE_KEY = ASH.ACADEMIC_SESSION
    INNER JOIN payroll_period PRT ON CLD.CALENDAR_DATE BETWEEN PRT.START_DATE AND PRT.END_DATE
    INNER JOIN academic_calendar ACL ON CLD.CALENDAR_DATE BETWEEN ACL.START_DATE AND ACL.END_DATE AND ACL.SessionPeriodId = ASH.SessionPeriodId
    WHERE PRT.ID = '$payrollCode' AND SES.CODE_NOM = '$user_sesion'
    ORDER BY CLD.CALENDAR_DATE ASC";

$sqlIncidenceReport = "SELECT 
    DISTINCT
    AAT.SESSION,
    ASH.PERSON_CODE_ID AS ID_PWC,
    ASH.ID_NOM,
    CONCAT(ASH.LAST_NAME,' ',ASH.Last_Name_Prefix,' ',ASH.NAME) AS DOC_NAME,
    AAT.PROGRAM,
    AAT.CURRICULUM,
    AAT.GENERAL_ED,
    AAT.EVENT_ID,
    (SELECT COUNT(ATT.AttendanceId) FROM academic_attendance ATT WHERE ATT.SESSION = AAT.SESSION AND ATT.ACADEMIC_ID = AAT.ACADEMIC_ID AND ATT.PROGRAM = AAT.PROGRAM AND ATT.CURRICULUM = AAT.CURRICULUM AND ATT.GENERAL_ED = AAT.GENERAL_ED AND ATT.EVENT_ID = AAT.EVENT_ID
        AND ATT.TINC IN ('1','2','3','4') AND ATT.IN_OUT = 1 AND ATT.ATTENDANCE_DATE BETWEEN (SELECT START_DATE FROM payroll_period WHERE ID = '$payrollCode') 
            AND (SELECT END_DATE FROM payroll_period WHERE ID = '$payrollCode')) CONT_ATTEN
    FROM academic_schedules ASH
    INNER JOIN academic_attendance AAT ON AAT.SCHEDULE_ID = ASH.PK
    INNER JOIN code_sesion_academic CSA ON AAT.SESSION = CSA.CODE_VALUE_KEY
    WHERE 
        AAT.ATTENDANCE_DATE BETWEEN (SELECT START_DATE FROM payroll_period WHERE ID = '$payrollCode') AND (SELECT END_DATE FROM payroll_period WHERE ID = '$payrollCode')
        AND CODE_NOM = '$user_sesion'
    ORDER BY AAT.ACADEMIC_ID, AAT.PROGRAM, AAT.CURRICULUM, AAT.GENERAL_ED ASC";
