<?php 



// Consulta para obtener la tabla del historial de asistencias de los empleados

$sql_paryrollPeriod_report = "SELECT DISTINCT EMP.ID_NOM
        , CONCAT(EMP.LAST_NAME,' ',EMP.LAST_NAME_PREFIX,' ',EMP.NAME) NOMBRE
        , DYS.NAME_DAY
        , CAL.CALENDAR_DATE
        , IFNULL( (SELECT CIN.DESCRIP_TINC FROM admin_attendance ATE INNER JOIN code_incidence CIN ON CIN.CODE_TINC = ATE.TINC WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 1 ORDER BY ATE.JUSTIFY DESC LIMIT 1), '') STATUS
        , IFNULL( (SELECT ATE.JUSTIFY FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 1 ORDER BY ATE.JUSTIFY DESC LIMIT 1), '') JUSTIFY
        , IFNULL( (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 1 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), '') CHECK_IN
        , IFNULL( (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 2 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), '') CHECK_OUT
        , IFNULL( (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 3 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), '') BREAK_START
        , IFNULL( (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 4 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), '') BREAK_END
        , IFNULL( TIMEDIFF(
                IFNULL( (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 4 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), ''),
                IFNULL( (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 3 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), '')), '') BREAK_TIME_TAKEN
        FROM admin_attendance ATT
                    INNER JOIN employed EMP ON EMP.ID_NOM = ATT.NOM_ID
                    INNER JOIN code_days DYS ON DYS.CODE_DAY = (DAYOFWEEK(ATTENDANCE_DATE) - 1)
                    INNER JOIN calendar CAL ON CAL.CALENDAR_DATE = ATT.ATTENDANCE_DATE
                    WHERE EMP.SUPERVISOR_ID = '$user_active' 
                        AND ATT.ATTENDANCE_DATE BETWEEN (SELECT START_DATE FROM payroll_period WHERE ID = '$payrollPeriodID') AND (SELECT END_DATE FROM payroll_period WHERE ID = '$payrollPeriodID')
        ORDER BY EMP.ID_NOM ASC, ATT.ATTENDANCE_DATE ASC;";



//echo $id_nom_employed;



$sql_paryrollPeriod_report_xlsx = "SELECT DISTINCT EMP.ID_NOM
        , CONCAT(EMP.LAST_NAME,' ',EMP.LAST_NAME_PREFIX,' ',EMP.NAME) NOMBRE
        , DYS.NAME_DAY
        , CAL.CALENDAR_DATE
        , IFNULL( (SELECT CIN.DESCRIP_TINC FROM admin_attendance ATE INNER JOIN code_incidence CIN ON CIN.CODE_TINC = ATE.TINC WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 1 ORDER BY ATE.JUSTIFY DESC LIMIT 1), '') STATUS
        , IFNULL( (SELECT ATE.JUSTIFY FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 1 ORDER BY ATE.JUSTIFY DESC LIMIT 1), '') JUSTIFY
        , IFNULL( (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 1 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), '') CHECK_IN
        , IFNULL( (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 2 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), '') CHECK_OUT
        , IFNULL( (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 3 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), '') BREAK_START
        , IFNULL( (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 4 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), '') BREAK_END
        , IFNULL( TIMEDIFF(
                IFNULL( (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 4 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), ''),
                IFNULL( (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 3 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), '')), '') BREAK_TIME_TAKEN
        FROM admin_attendance ATT
                    INNER JOIN employed EMP ON EMP.ID_NOM = ATT.NOM_ID
                    INNER JOIN code_days DYS ON DYS.CODE_DAY = (DAYOFWEEK(ATTENDANCE_DATE) - 1)
                    INNER JOIN calendar CAL ON CAL.CALENDAR_DATE = ATT.ATTENDANCE_DATE
                    WHERE EMP.SUPERVISOR_ID = '$user_active' 
                        AND ATT.ATTENDANCE_DATE BETWEEN (SELECT START_DATE FROM payroll_period WHERE ID = '$payrollPeriodID') AND (SELECT END_DATE FROM payroll_period WHERE ID = '$payrollPeriodID')
        ORDER BY EMP.ID_NOM ASC, ATT.ATTENDANCE_DATE ASC;";



//Reporte Excel



$sql_payrollPeriod_calendar = "SELECT
    DISTINCT
        CAL.CALENDAR_DATE
    FROM calendar CAL
    INNER JOIN payroll_period PRP ON CAL.CALENDAR_DATE BETWEEN PRP.START_DATE AND PRP.END_DATE
    WHERE PRP.ID = '$payrollPeriodID'";



?>