<?php 

$codeDayCheck = date('w');
//$codeDayCheck = '5';
$today = date('Y-m-d');

/** Módulo Asistencias */

//Horarios
$sql_academic_schedules = "SELECT 
        DISTINCT 
        ASH.EVENT, ASH.ROOM,
        (SELECT DISTINCT SCH.START_CLASS FROM academic_schedules SCH WHERE SCH.EVENT = ASH.EVENT AND SCH.SessionPeriodId = ACL.SessionPeriodId AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM = ASH.ROOM AND SCH.START_CLASS = ASH.START_CLASS AND SCH.CODE_DAY = '1') START_MONDAY,
        (SELECT DISTINCT SCH.START_CLASS FROM academic_schedules SCH WHERE SCH.EVENT = ASH.EVENT AND SCH.SessionPeriodId = ACL.SessionPeriodId AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM = ASH.ROOM AND SCH.START_CLASS = ASH.START_CLASS AND SCH.CODE_DAY = '2') START_TUESDAY,
        (SELECT DISTINCT SCH.START_CLASS FROM academic_schedules SCH WHERE SCH.EVENT = ASH.EVENT AND SCH.SessionPeriodId = ACL.SessionPeriodId AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM = ASH.ROOM AND SCH.START_CLASS = ASH.START_CLASS AND SCH.CODE_DAY = '3') START_WEDNESDAY,
        (SELECT DISTINCT SCH.START_CLASS FROM academic_schedules SCH WHERE SCH.EVENT = ASH.EVENT AND SCH.SessionPeriodId = ACL.SessionPeriodId AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM = ASH.ROOM AND SCH.START_CLASS = ASH.START_CLASS AND SCH.CODE_DAY = '4') START_THURSDAY,
        (SELECT DISTINCT SCH.START_CLASS FROM academic_schedules SCH WHERE SCH.EVENT = ASH.EVENT AND SCH.SessionPeriodId = ACL.SessionPeriodId AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM = ASH.ROOM AND SCH.START_CLASS = ASH.START_CLASS AND SCH.CODE_DAY = '5') START_FRIDAY,
        (SELECT DISTINCT SCH.START_CLASS FROM academic_schedules SCH WHERE SCH.EVENT = ASH.EVENT AND SCH.SessionPeriodId = ACL.SessionPeriodId AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM = ASH.ROOM AND SCH.START_CLASS = ASH.START_CLASS AND SCH.CODE_DAY = '6') START_SATURDAY,
        (SELECT DISTINCT SCH.START_CLASS FROM academic_schedules SCH WHERE SCH.EVENT = ASH.EVENT AND SCH.SessionPeriodId = ACL.SessionPeriodId AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM = ASH.ROOM AND SCH.START_CLASS = ASH.START_CLASS AND SCH.CODE_DAY = '0') START_SUNDAY,
        (SELECT DISTINCT SCH.END_CLASS FROM academic_schedules SCH WHERE SCH.EVENT = ASH.EVENT AND SCH.SessionPeriodId = ACL.SessionPeriodId AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM = ASH.ROOM AND SCH.START_CLASS = ASH.START_CLASS AND SCH.CODE_DAY = '1') END_MONDAY,
        (SELECT DISTINCT SCH.END_CLASS FROM academic_schedules SCH WHERE SCH.EVENT = ASH.EVENT AND SCH.SessionPeriodId = ACL.SessionPeriodId AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM = ASH.ROOM AND SCH.START_CLASS = ASH.START_CLASS AND SCH.CODE_DAY = '2') END_TUESDAY,
        (SELECT DISTINCT SCH.END_CLASS FROM academic_schedules SCH WHERE SCH.EVENT = ASH.EVENT AND SCH.SessionPeriodId = ACL.SessionPeriodId AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM = ASH.ROOM AND SCH.START_CLASS = ASH.START_CLASS AND SCH.CODE_DAY = '3') END_WEDNESDAY,
        (SELECT DISTINCT SCH.END_CLASS FROM academic_schedules SCH WHERE SCH.EVENT = ASH.EVENT AND SCH.SessionPeriodId = ACL.SessionPeriodId AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM = ASH.ROOM AND SCH.START_CLASS = ASH.START_CLASS AND SCH.CODE_DAY = '4') END_THURSDAY,
        (SELECT DISTINCT SCH.END_CLASS FROM academic_schedules SCH WHERE SCH.EVENT = ASH.EVENT AND SCH.SessionPeriodId = ACL.SessionPeriodId AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM = ASH.ROOM AND SCH.START_CLASS = ASH.START_CLASS AND SCH.CODE_DAY = '5') END_FRIDAY,
        (SELECT DISTINCT SCH.END_CLASS FROM academic_schedules SCH WHERE SCH.EVENT = ASH.EVENT AND SCH.SessionPeriodId = ACL.SessionPeriodId AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM = ASH.ROOM AND SCH.START_CLASS = ASH.START_CLASS AND SCH.CODE_DAY = '6') END_SATURDAY,
        (SELECT DISTINCT SCH.END_CLASS FROM academic_schedules SCH WHERE SCH.EVENT = ASH.EVENT AND SCH.SessionPeriodId = ACL.SessionPeriodId AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM = ASH.ROOM AND SCH.START_CLASS = ASH.START_CLASS AND SCH.CODE_DAY = '0') END_SUNDAY
    FROM academic_schedules ASH
    INNER JOIN academic_calendar ACL ON ACL.SessionPeriodId = ASH.SessionPeriodId
    WHERE ASH.PERSON_CODE_ID = '$user_active'
        AND ACL.START_DATE <= '$today' AND ACL.END_DATE >= '$today'";

//Check in - Check out
$sql_academic_check = "SELECT
        ASH.PK, ASH.PERSON_CODE_ID ID, ASH.CODE_DAY DY, ASH.ACADEMIC_SESSION SESION, ASH.DEGREE DEGREE, ASH.PROGRAM PROGRAM, ASH.CURRICULUM CURRICULUM, ASH.ROOM ROOM, ASH.EVENT MAT,
        ASH.MAX_BEFORE_CLASS, ASH.START_CLASS, ASH.DELAY_CLASS, ASH.MAX_DELAY_CLASS, ASH.MIN_END_CLASS, ASH.END_CLASS, ASH.ACADEMIC_TERM,
        IFNULL( (SELECT DISTINCT ATT.ATTENDANCE_DATE FROM academic_attendance ATT WHERE ASH.PERSON_CODE_ID = ATT.ACADEMIC_ID AND ASH.CODE_DAY = ATT.CODE_DAY AND ASH.ACADEMIC_SESSION = ATT.SESSION AND ASH.CURRICULUM = ATT.CURRICULUM AND ASH.PROGRAM = ATT.PROGRAM AND ASH.DEGREE = ATT.DEGREE AND ASH.EVENT = ATT.EVENT_ID AND ASH.ROOM = ATT.ROOM_ID AND ATT.ATTENDANCE_DATE = '$today' AND ATT.START_CLASS = ASH.START_CLASS AND ATT.END_CLASS = ASH.END_CLASS), '') ATTENDANCE_DATE,
        IFNULL( (SELECT DISTINCT ATT.TINC FROM academic_attendance ATT WHERE ASH.PERSON_CODE_ID = ATT.ACADEMIC_ID AND ASH.CODE_DAY = ATT.CODE_DAY AND ASH.ACADEMIC_SESSION = ATT.SESSION AND ASH.CURRICULUM = ATT.CURRICULUM AND ASH.PROGRAM = ATT.PROGRAM AND ASH.DEGREE = ATT.DEGREE AND ASH.EVENT = ATT.EVENT_ID AND ASH.ROOM = ATT.ROOM_ID AND ATT.ATTENDANCE_DATE = '$today' AND ATT.START_CLASS = ASH.START_CLASS AND ATT.END_CLASS = ASH.END_CLASS AND ATT.IN_OUT = 1 ), '') TINC,
        IFNULL( (SELECT DISTINCT ATT.ATTENDANCE_TIME FROM academic_attendance ATT WHERE ASH.PERSON_CODE_ID = ATT.ACADEMIC_ID AND ASH.CODE_DAY = ATT.CODE_DAY AND ASH.ACADEMIC_SESSION = ATT.SESSION AND ASH.CURRICULUM = ATT.CURRICULUM AND ASH.PROGRAM = ATT.PROGRAM AND ASH.DEGREE = ATT.DEGREE AND ASH.EVENT = ATT.EVENT_ID AND ASH.ROOM = ATT.ROOM_ID AND ATT.ATTENDANCE_DATE = '$today' AND ATT.START_CLASS = ASH.START_CLASS AND ATT.END_CLASS = ASH.END_CLASS AND ATT.IN_OUT = 1 ), '') CHECK_IN,
        IFNULL( (SELECT DISTINCT ATT.ATTENDANCE_TIME FROM academic_attendance ATT WHERE ASH.PERSON_CODE_ID = ATT.ACADEMIC_ID AND ASH.CODE_DAY = ATT.CODE_DAY AND ASH.ACADEMIC_SESSION = ATT.SESSION AND ASH.CURRICULUM = ATT.CURRICULUM AND ASH.PROGRAM = ATT.PROGRAM AND ASH.DEGREE = ATT.DEGREE AND ASH.EVENT = ATT.EVENT_ID AND ASH.ROOM = ATT.ROOM_ID AND ATT.ATTENDANCE_DATE = '$today' AND ATT.START_CLASS = ASH.START_CLASS AND ATT.END_CLASS = ASH.END_CLASS AND ATT.IN_OUT = 2 ), '') CHECK_OUT,
        IFNULL( (SELECT DISTINCT ATT.CLASS_SUMMARY FROM academic_attendance ATT WHERE ASH.PERSON_CODE_ID = ATT.ACADEMIC_ID AND ASH.CODE_DAY = ATT.CODE_DAY AND ASH.ACADEMIC_SESSION = ATT.SESSION AND ASH.CURRICULUM = ATT.CURRICULUM AND ASH.PROGRAM = ATT.PROGRAM AND ASH.DEGREE = ATT.DEGREE AND ASH.EVENT = ATT.EVENT_ID AND ASH.ROOM = ATT.ROOM_ID AND ATT.ATTENDANCE_DATE = '$today' AND ATT.START_CLASS = ASH.START_CLASS AND ATT.END_CLASS = ASH.END_CLASS AND ATT.IN_OUT = 1 ), '') CLASS_SUMMARY,
        IFNULL( (SELECT DISTINCT ATT.JUSTIFY FROM academic_attendance ATT WHERE ASH.PERSON_CODE_ID = ATT.ACADEMIC_ID AND ASH.CODE_DAY = ATT.CODE_DAY AND ASH.ACADEMIC_SESSION = ATT.SESSION AND ASH.CURRICULUM = ATT.CURRICULUM AND ASH.PROGRAM = ATT.PROGRAM AND ASH.DEGREE = ATT.DEGREE AND ASH.EVENT = ATT.EVENT_ID AND ASH.ROOM = ATT.ROOM_ID AND ATT.ATTENDANCE_DATE = '$today' AND ATT.START_CLASS = ASH.START_CLASS AND ATT.END_CLASS = ASH.END_CLASS AND ATT.IN_OUT = 1 ), '') JUSTIFY
    FROM academic_schedules ASH
    INNER JOIN academic_calendar CAL ON CAL.SessionPeriodId = ASH.SessionPeriodId
    WHERE ASH.PERSON_CODE_ID = '$user_active' AND CAL.START_DATE <= '$today' AND CAL.END_DATE >= '$today' AND CODE_DAY = '$codeDayCheck'
    ORDER BY CHECK_OUT ASC, CHECK_IN DESC, ASH.START_CLASS ASC";

$sql_get_attendance = "SELECT DISTINCT
        DYS.NAME_DAY, ATD.ATTENDANCE_DATE, ATD.DEGREE, ATD.PROGRAM, ATD.CURRICULUM, ATD.EVENT_ID, ATD.ROOM_ID, 
        (SELECT TIN.DESCRIP_TINC FROM academic_attendance DAT 
    INNER JOIN code_incidence TIN ON TIN.CODE_TINC = DAT.TINC WHERE DAT.SCHEDULE_ID = ATD.SCHEDULE_ID AND DAT.ATTENDANCE_DATE = ATD.ATTENDANCE_DATE AND DAT.IN_OUT = 1 ORDER BY DAT.ATTENDANCE_TIME DESC LIMIT 1) DESCRIP_TINC,
        (SELECT DAT.ATTENDANCE_TIME FROM academic_attendance DAT WHERE DAT.SCHEDULE_ID = ATD.SCHEDULE_ID AND DAT.ATTENDANCE_DATE = ATD.ATTENDANCE_DATE AND DAT.IN_OUT = 1 ORDER BY DAT.ATTENDANCE_TIME DESC LIMIT 1) CHECK_IN,
        (SELECT DAT.ATTENDANCE_TIME FROM academic_attendance DAT WHERE DAT.SCHEDULE_ID = ATD.SCHEDULE_ID AND DAT.ATTENDANCE_DATE = ATD.ATTENDANCE_DATE AND DAT.IN_OUT = 2 ORDER BY DAT.ATTENDANCE_TIME DESC LIMIT 1) CHECK_OUT,
        (SELECT DAT.JUSTIFY FROM academic_attendance DAT WHERE DAT.SCHEDULE_ID = ATD.SCHEDULE_ID AND DAT.ATTENDANCE_DATE = ATD.ATTENDANCE_DATE AND DAT.IN_OUT = 1  ORDER BY DAT.JUSTIFY DESC LIMIT 1) JUSTIFY
    FROM academic_attendance ATD 
    INNER JOIN code_days DYS ON DYS.CODE_DAY = ATD.CODE_DAY
    WHERE ATD.ACADEMIC_ID = '$user_active' AND ATD.ATTENDANCE_DATE BETWEEN (SELECT PRP.START_DATE FROM payroll_period PRP WHERE ID = '$payrollPeriodID') AND (SELECT PRP.END_DATE FROM payroll_period PRP WHERE ID = '$payrollPeriodID')
    ORDER BY ATD.ATTENDANCE_DATE ASC, CHECK_IN ASC";

$sql_countDelays = "SELECT DISTINCT
    AAT.ATTENDANCE_DATE, AAT.EVENT_ID, COUNT(AAT.TINC) TINC
    FROM academic_attendance AAT
    INNER JOIN payroll_period PRP ON AAT.ATTENDANCE_DATE BETWEEN PRP.START_DATE AND PRP.END_DATE
    WHERE '$today' BETWEEN PRP.START_DATE AND PRP.END_DATE AND AAT.TINC IN (2,8) AND AAT.IN_OUT = 1 AND AAT.ACADEMIC_ID = '$user_active'
    ORDER BY AAT.ATTENDANCE_DATE";

?>