<?php
//Días solicitados ya depurados
$sql_getCalendarDays = "SELECT 
	COUNT(CAL.CALENDAR_DATE) DAYS_REQ,
	(SELECT CDT.CALENDAR_DATE FROM calendar CDT 
     	INNER JOIN admin_schedules ASH ON ASH.CODE_DAY = CDT.CODE_DAY
        INNER JOIN employed EMP ON EMP.SCHEDULE_GROUP = ASH.CODE_SCHEDULE
        WHERE EMP.ID_NOM = '$idnom' AND DAY_OF_REST != 1
			AND CDT.CALENDAR_DATE BETWEEN '$start_date' AND '$end_date' 
     	ORDER BY CDT.CALENDAR_DATE ASC
    	LIMIT 1) START_DATE,
    (SELECT CDT.CALENDAR_DATE FROM calendar CDT 
     	INNER JOIN admin_schedules ASH ON ASH.CODE_DAY = CDT.CODE_DAY
        INNER JOIN employed EMP ON EMP.SCHEDULE_GROUP = ASH.CODE_SCHEDULE
        WHERE EMP.ID_NOM = '$idnom' AND DAY_OF_REST != 1
			AND CDT.CALENDAR_DATE BETWEEN '$start_date' AND '$end_date' 
     	ORDER BY CDT.CALENDAR_DATE DESC
    	LIMIT 1) END_DATE
FROM calendar CAL
INNER JOIN admin_schedules ASH ON ASH.CODE_DAY = CAL.CODE_DAY
INNER JOIN employed EMP ON EMP.SCHEDULE_GROUP = ASH.CODE_SCHEDULE
WHERE EMP.ID_NOM = '$idnom' AND DAY_OF_REST != 1
	AND CAL.CALENDAR_DATE BETWEEN '$start_date' AND '$end_date';";

$sqlDownloadVacations = "SELECT 
DISTINCT EMP.ID_NOM ID_NOM, CONCAT(EMP.LAST_NAME,' ',EMP.LAST_NAME_PREFIX,' ',EMP.NAME) EMP_NAME,
(YEAR(NOW()) - YEAR(EMP.ANTIQUITY)) YEARS, CVC.DAYS_BY_LAW,
( SELECT IF(SUM(VR2.DAYS_REQUESTED) IS NULL, '-', SUM(VR2.DAYS_REQUESTED)) FROM vacation_request VR2 WHERE VR2.ID_NOM = EMP.ID_NOM AND VR2.AUTHORIZATION_FLAG != '2' AND VR2.REQUEST_TERM = YEAR(NOW()) AND MONTH(VR2.START_DATE) = '1' ) JANUARY,
( SELECT IF(SUM(VR2.DAYS_REQUESTED) IS NULL, '-', SUM(VR2.DAYS_REQUESTED)) FROM vacation_request VR2 WHERE VR2.ID_NOM = EMP.ID_NOM AND VR2.AUTHORIZATION_FLAG != '2' AND VR2.REQUEST_TERM = YEAR(NOW()) AND MONTH(VR2.START_DATE) = '2' ) FEBRUARY,
( SELECT IF(SUM(VR2.DAYS_REQUESTED) IS NULL, '-', SUM(VR2.DAYS_REQUESTED)) FROM vacation_request VR2 WHERE VR2.ID_NOM = EMP.ID_NOM AND VR2.AUTHORIZATION_FLAG != '2' AND VR2.REQUEST_TERM = YEAR(NOW()) AND MONTH(VR2.START_DATE) = '3' ) MARCH,
( SELECT IF(SUM(VR2.DAYS_REQUESTED) IS NULL, '-', SUM(VR2.DAYS_REQUESTED)) FROM vacation_request VR2 WHERE VR2.ID_NOM = EMP.ID_NOM AND VR2.AUTHORIZATION_FLAG != '2' AND VR2.REQUEST_TERM = YEAR(NOW()) AND MONTH(VR2.START_DATE) = '4' ) APRIL,
( SELECT IF(SUM(VR2.DAYS_REQUESTED) IS NULL, '-', SUM(VR2.DAYS_REQUESTED)) FROM vacation_request VR2 WHERE VR2.ID_NOM = EMP.ID_NOM AND VR2.AUTHORIZATION_FLAG != '2' AND VR2.REQUEST_TERM = YEAR(NOW()) AND MONTH(VR2.START_DATE) = '5' ) MAY,
( SELECT IF(SUM(VR2.DAYS_REQUESTED) IS NULL, '-', SUM(VR2.DAYS_REQUESTED)) FROM vacation_request VR2 WHERE VR2.ID_NOM = EMP.ID_NOM AND VR2.AUTHORIZATION_FLAG != '2' AND VR2.REQUEST_TERM = YEAR(NOW()) AND MONTH(VR2.START_DATE) = '6' ) JUNE,
( SELECT IF(SUM(VR2.DAYS_REQUESTED) IS NULL, '-', SUM(VR2.DAYS_REQUESTED)) FROM vacation_request VR2 WHERE VR2.ID_NOM = EMP.ID_NOM AND VR2.AUTHORIZATION_FLAG != '2' AND VR2.REQUEST_TERM = YEAR(NOW()) AND MONTH(VR2.START_DATE) = '7' ) JULY,
( SELECT IF(SUM(VR2.DAYS_REQUESTED) IS NULL, '-', SUM(VR2.DAYS_REQUESTED)) FROM vacation_request VR2 WHERE VR2.ID_NOM = EMP.ID_NOM AND VR2.AUTHORIZATION_FLAG != '2' AND VR2.REQUEST_TERM = YEAR(NOW()) AND MONTH(VR2.START_DATE) = '8' ) AUGUST,
( SELECT IF(SUM(VR2.DAYS_REQUESTED) IS NULL, '-', SUM(VR2.DAYS_REQUESTED)) FROM vacation_request VR2 WHERE VR2.ID_NOM = EMP.ID_NOM AND VR2.AUTHORIZATION_FLAG != '2' AND VR2.REQUEST_TERM = YEAR(NOW()) AND MONTH(VR2.START_DATE) = '9' ) SEPTEMBER,
( SELECT IF(SUM(VR2.DAYS_REQUESTED) IS NULL, '-', SUM(VR2.DAYS_REQUESTED)) FROM vacation_request VR2 WHERE VR2.ID_NOM = EMP.ID_NOM AND VR2.AUTHORIZATION_FLAG != '2' AND VR2.REQUEST_TERM = YEAR(NOW()) AND MONTH(VR2.START_DATE) = '10' ) OCTOBER,
( SELECT IF(SUM(VR2.DAYS_REQUESTED) IS NULL, '-', SUM(VR2.DAYS_REQUESTED)) FROM vacation_request VR2 WHERE VR2.ID_NOM = EMP.ID_NOM AND VR2.AUTHORIZATION_FLAG != '2' AND VR2.REQUEST_TERM = YEAR(NOW()) AND MONTH(VR2.START_DATE) = '11' ) NOVEMBER,
( SELECT IF(SUM(VR2.DAYS_REQUESTED) IS NULL, '-', SUM(VR2.DAYS_REQUESTED)) FROM vacation_request VR2 WHERE VR2.ID_NOM = EMP.ID_NOM AND VR2.AUTHORIZATION_FLAG != '2' AND VR2.REQUEST_TERM = YEAR(NOW()) AND MONTH(VR2.START_DATE) = '12' ) DECEMBER,
( SELECT IF(SUM(VR2.DAYS_REQUESTED) IS NULL, '0', SUM(VR2.DAYS_REQUESTED)) FROM vacation_request VR2 WHERE VR2.ID_NOM = EMP.ID_NOM AND VR2.AUTHORIZATION_FLAG != '2' AND VR2.REQUEST_TERM = YEAR(NOW()) ) DAYS
FROM employed EMP
LEFT OUTER JOIN vacation_request VRQ ON EMP.ID_NOM = VRQ.ID_NOM
LEFT OUTER JOIN code_vacation CVC ON (YEAR(NOW()) - YEAR(EMP.ANTIQUITY)) BETWEEN CVC.MIN_YEARS AND CVC.MAX_YEARS;";

?>